#!/usr/bin/env python3
"""SessionStart hook for the `roles` plugin.

Lazy and non-littering: it acts ONLY in repos that already have a
`.claude/roles/` directory (created on first actual use of a role, not on
install) — so installing the plugin globally never scatters role files into
unrelated repos.

When the registry exists it does two safe, read-mostly jobs:

  1. Index — regenerate `.claude/roles/registry.md` (name + charter per shared
     core role file). `crew.md` / `panel.md` are consumer registries, not cores.
  2. Audit — emit a graduation/bloat recommendation as SessionStart
     additionalContext when a role's solo-learnings grow large, or a role name
     appears in both `crew.md` and `panel.md` (cross-context → review for
     graduation to the shared core). Never rewrites a role file: graduation is
     user-gated.

Role files are created lazily by the skills themselves (each wrapper seeds its
own `role.md` into `.claude/roles/<role>.md` on first use). Exits 0 always.
"""
from __future__ import annotations

import json
import os
import re
import sys

ROLES_DIR = os.path.join(".claude", "roles")
CONSUMER_FILES = {"crew.md", "panel.md", "registry.md"}
T_SOLO_LINES = 15

REGISTRY_HEADER = """# Roles registry (index)

Auto-generated by the `roles` plugin hook — do not edit; edit the role files.
Consumer registries: `crew.md` (dev-crew) · `panel.md` (brainstorm-panel).

| Role | Charter |
| --- | --- |
"""


def charter_of(path: str) -> str:
    try:
        text = open(path, encoding="utf-8").read()
    except OSError:
        return ""
    m = re.search(r"^## Charter\s*\n+([^\n#].*)$", text, re.M)
    return m.group(1).strip() if m else ""


def solo_learning_count(path: str) -> int:
    try:
        text = open(path, encoding="utf-8").read()
    except OSError:
        return 0
    m = re.search(r"^## Learnings \(solo\)\n(.*?)(?=^## |\Z)", text, re.M | re.S)
    if not m:
        return 0
    return sum(1 for ln in m.group(1).splitlines() if ln.lstrip().startswith("- "))


def role_names_in(path: str) -> set[str]:
    """Role names referenced by a consumer registry (### headings + role: links)."""
    try:
        text = open(path, encoding="utf-8").read()
    except OSError:
        return set()
    names = set(re.findall(r"^### ([a-z][a-z0-9-]*)\s*$", text, re.M))
    names |= set(re.findall(r"^\s*-\s*role:\s*([a-z][a-z0-9-]*)\s*$", text, re.M))
    return names


def main() -> int:
    # Lazy: do nothing unless this repo has opted into roles already.
    if not os.path.isdir(ROLES_DIR):
        return 0

    # 1. regenerate the index over shared core role files
    cores = sorted(
        f for f in os.listdir(ROLES_DIR)
        if f.endswith(".md") and f not in CONSUMER_FILES
    )
    try:
        with open(os.path.join(ROLES_DIR, "registry.md"), "w", encoding="utf-8") as idx:
            idx.write(REGISTRY_HEADER)
            for f in cores:
                idx.write(f"| {f[:-3]} | {charter_of(os.path.join(ROLES_DIR, f))} |\n")
    except OSError:
        pass

    # 2. audit
    notes: list[str] = []
    for f in cores:
        n = solo_learning_count(os.path.join(ROLES_DIR, f))
        if n > T_SOLO_LINES:
            notes.append(
                f"role '{f[:-3]}' has {n} solo learnings — review for graduation to "
                f"'## Learnings (core)' (user-gated) and prune the rest."
            )
    crew = role_names_in(os.path.join(ROLES_DIR, "crew.md"))
    panel = role_names_in(os.path.join(ROLES_DIR, "panel.md"))
    for name in sorted(crew & panel):
        notes.append(
            f"role '{name}' is used by both crew and panel — review both registries' "
            f"learnings for context-independent lessons to graduate to the shared core."
        )

    if notes:
        print(json.dumps({
            "hookSpecificOutput": {
                "hookEventName": "SessionStart",
                "additionalContext": "roles registry audit: " + " | ".join(notes),
            }
        }))
    return 0


if __name__ == "__main__":
    sys.exit(main())
